storm:
  authz:
    policies:
    - sa: test.vo
      actions:
      - all
      effect: permit
      description: Grant read/write access to test.vo VOMS users and iam-dev tokens
      principals:
      - type: vo
        params:
          vo: test.vo
      - type: jwt-issuer
        params:
          iss: https://iam-dev.cloud.cnaf.infn.it/
      - type: x509-subject
        params:
          subject: CN=Federica Agostini fagostin@infn.it,O=Istituto Nazionale di Fisica Nucleare,C=IT,DC=tcs,DC=terena,DC=org
    - sa: dteam
      actions:
      - all
      effect: permit
      description: Grant read/write access to dteam VOMS users and iam-dteam tokens
      principals:
      - type: vo
        params:
          vo: dteam
      - type: jwt-issuer
        params:
          iss: https://dteam-auth.cern.ch/
      - type: x509-subject
        params:
          subject: CN=Federica Agostini fagostin@infn.it,O=Istituto Nazionale di Fisica Nucleare,C=IT,DC=tcs,DC=terena,DC=org

