oauth:
  enable-oidc: true
  issuers:
  - name: dteam
    issuer: https://dteam-auth.cern.ch/
  - name: testvo
    issuer: https://iam-dev.cloud.cnaf.infn.it/

spring:
  security:
    oauth2:
      client:
        provider:
          dteam:
            issuer-uri: https://dteam-auth.cern.ch/
          testvo:
            issuer-uri: https://iam-dev.cloud.cnaf.infn.it/
        registration:
          dteam:
            provider: dteam
            authorization-grant-type: authorization_code
            client-name: dteam
            client-id: ${DTEAM_CLIENT_ID:-client}
            client-secret: ${DTEAM_CLIENT_SECRET:-secret}
            scope:
            - openid
            - profile
          testvo:
            provider: testvo
            authorization-grant-type: authorization_code
            client-name: testvo
            client-id: ${TESTVO_CLIENT_ID:-client}
            client-secret: ${TESTVO_CLIENT_SECRET:-secret}
            scope:
            - openid
            - profile